# Generated by Django 5.2.4 on 2025-07-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('Did', models.AutoField(primary_key=True, serialize=False)),
                ('DoctorName', models.CharField(max_length=100)),
                ('specialist', models.CharField(max_length=200)),
                ('Block', models.CharField(max_length=100)),
                ('Roomno', models.IntegerField()),
            ],
        ),
    ]
