# Generated by Django 5.2.4 on 2025-07-09 02:15

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('Pid', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=150)),
                ('Age', models.IntegerField()),
                ('Sex', models.CharField(max_length=20)),
                ('Dateorbirth', models.DateField()),
                ('Phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Address', models.TextField()),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Issue', models.TextField()),
                ('DoctorName', models.CharField(max_length=100)),
                ('Block', models.CharField(max_length=100)),
                ('Roomno', models.IntegerField()),
                ('Did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ey.doctors')),
            ],
        ),
    ]
